### ISSUE TITLE
Saba Yashfeen

### ISSUE THREAD

**Issue by sabay79** [musmanrafiq/dotnet_web_bootcamp#25]
I've created a class which has a function that returns a numeric value after computation. I've inherited a class from it which also uses the same function that of parent class (I have not created function body in derived class) but the value to be entered is different and not default one. Is this inheritance or polymorphism?

**Comment by musmanrafiq** [comment]
No, that is not polymorphism. Though we can say its inheritance but I wonder why in parent's method is giving different value, can you add you code snippet here in the comment.

**Comment by sabay79** [comment]
internal class Vehicle
    {
        public string brand = "Ford";
        private int launchYear = 1903;
        public int LaunchYear
        {
            get { return launchYear; }
            set { launchYear = value; }
        }
        public int TimePeriod()
        { return (2022 - launchYear); }
    }

 internal class Car : Vehicle
    {
        public string model = "Mustang";
    }


static void Main()
        {
            Car car = new Car();
            Console.WriteLine("\nBrand: {0}\nLaunch Date: {1}\n" +
                "{2} was launched {3} years ago.", car.brand, car.LaunchYear, car.brand, car.TimePeriod());

            car.LaunchYear = 1964;
            Console.WriteLine("Model: {0}\nLaunch Date: {1}\n" +
                "{2} was launched {3} years ago.\n", car.model, car.LaunchYear, car.model, car.TimePeriod());
        }

**Comment by sabay79** [comment]
**Output**

Brand: Ford
Launch Date: 1903
Ford was launched 119 years ago.
Model: Mustang
Launch Date: 1964
Mustang was launched 58 years ago.

**Comment by musmanrafiq** [comment]
Now I got your point by looking at the above code snippet, yes that's inheritance.

**Comment by musmanrafiq** [comment]
And if you want that, the child class should able to set its own values of the parent's properties, we can do it like this:

internal class Car : Vehicle

{
    public Car(){
      this.LaunchYear = 2023;
    }
}

// Now car object should return launch year of 2023

**Comment by sabay79** [comment]
Understood! Thank you so much Sir.
